language: node_js
node_js:
- 6.1
script:
- npm run build
notifications:
  slack:
    secure: URXU5XR27EVzXVpiMlxc6FI/lTnMZHUrn7DtJmefu+3g8u+D0beKymf3c8hWQ4m08jSCE6Pc1iGDu8Gkw4wyg0L75mkCbSdnlmyv4C7xULk4Ey+y6jTAxT52iC17rSGiUd7rJMPm+2uVinmFS6W+cTm91/GdyrnQPQuxzcSP+bYHF+aUqJxO5GhiV8kY0lOpLh76VFPCCICA9YUvlNzZ5+HUH5yD02NoNkmxUuLs9g99P2hBiNRcrNhuiVGWJybrPGVUR+vd9luOwz7mmhuLjjbgmi0yKSfl/MnKLhoSEKc5mIOmQ6pSsLxY4ogaJbSLY9/XBuyeCF8J5wgH4Lm/mxPIuT4X0C8N5qcpV8NUVnR3z0WaFbiKul9t0h3+9z5hZ0mfUT/L2UIZNvWy+VG7gVcFlLZZFQQ0gOEOuIVvCetDXE1/oiCYg9QLKPEQT4O9EJeY2jKNuFTSf0hujseAQ4AByk+xeuGMkpSByTim1MmxLZ1cpBmjeuIV5TvnSLtQxAROmkb/7t60uLyoNeaNPkwUtXv7X2IZR1LFecrzZWWHPYrIjw9Qh9l1bP1Xz6e4/BlObcvEBZbm7hBR9K7+Dq9QgKZdqL1tIgY0pFmBYuyyNPGhuxkdxXnPhyHkDsRw87/lqfQTLveJCTqbB0PX6bL+HejDVH4dcSQXd56dXos=
